#include <stdio.h>
#include <stdlib.h>
#include "chip8080.h"
#include "tools.h"

int disassemble_machine_code(unsigned char *codebuffer, int pc) {
    /* disassembles a binary file
     * codebuffer is a pointer to 8080 assembly code 
     * , pc is the current offset into the code 
     * return the number of bytes of the op */

    unsigned char *code = &codebuffer[pc];
    int opbytes = 1;

    printf("%04x ", pc);

    switch (*code) {
        case 0x00: printf("NOP"); printf("\n"); break;
        case 0x01: printf("LXI    B,#$%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0x02: printf("STAX   B"); printf("\n"); break;
        case 0x03: printf("INX    B"); printf("\n"); break;
        case 0x04: printf("INR    B"); printf("\n"); break;
        case 0x05: printf("DCR    B"); printf("\n"); break;
        case 0x06: printf("MVI    B,#$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0x07: printf("RLC"); printf("\n"); break;
        case 0x08: printf("NOP"); printf("\n"); break;
        case 0x09: printf("DAD    B"); printf("\n"); break;
        case 0x0a: printf("LDAX   B"); printf("\n"); break;
        case 0x0b: printf("DCX    B"); printf("\n"); break;
        case 0x0c: printf("INR    C"); printf("\n"); break;
        case 0x0d: printf("DCR    C"); printf("\n"); break;
        case 0x0e: printf("MVI    C,#$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0x0f: printf("RRC"); printf("\n"); break;
        case 0x10: printf("NOP"); printf("\n"); break;
        case 0x11: printf("LXI    D,#$%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0x12: printf("STAX   D"); printf("\n"); break;
        case 0x13: printf("INX    D"); printf("\n"); break;
        case 0x14: printf("INR    D"); printf("\n"); break;
        case 0x15: printf("DCR    D"); printf("\n"); break;
        case 0x16: printf("MVI    D,#$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0x17: printf("RAL"); printf("\n"); break;
        case 0x18: printf("NOP"); printf("\n"); break;
        case 0x19: printf("DAD    D"); printf("\n"); break;
        case 0x1a: printf("LDAX   D"); printf("\n"); break;
        case 0x1b: printf("DCX    D"); printf("\n"); break;
        case 0x1c: printf("INR    E"); printf("\n"); break;
        case 0x1d: printf("DCR    E"); printf("\n"); break;
        case 0x1e: printf("MVI    E,#$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0x1f: printf("RAR"); printf("\n"); break;
        case 0x20: printf("NOP"); printf("\n"); break;
        case 0x21: printf("LXI    H,#$%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0x22: printf("SHLD   $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0x23: printf("INX    H"); printf("\n"); break;
        case 0x24: printf("INR    H"); printf("\n"); break;
        case 0x25: printf("DCR    H"); printf("\n"); break;
        case 0x26: printf("MVI    H,#$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0x27: printf("DAA"); printf("\n"); break;
        case 0x28: printf("NOP"); printf("\n"); break;
        case 0x29: printf("DAD    H"); printf("\n"); break;
        case 0x2a: printf("LDHL   $%02x%02x", code[2], code[1]); printf("\n"); break;
        case 0x2b: printf("DCX    H"); printf("\n"); break;
        case 0x2c: printf("INR    L"); printf("\n"); break;
        case 0x2d: printf("DCR    L"); printf("\n"); break;
        case 0x2e: printf("MVI    L,#$%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0x2f: printf("CMA"); printf("\n"); break;
        case 0x30: printf("NOP"); printf("\n"); break;
        case 0x31: printf("LXI    SP,#$%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0x32: printf("STA    $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0x33: printf("INX    SP"); printf("\n"); break;
        case 0x34: printf("INR    M"); printf("\n"); break;
        case 0x35: printf("DCR    M"); printf("\n"); break;
        case 0x36: printf("MVI    M,#$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0x37: printf("SCT"); printf("\n"); break;
        case 0x38: printf("NOP"); printf("\n"); break;
        case 0x39: printf("DAD    SP"); printf("\n"); break;
        case 0x3a: printf("LDA    $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0x3b: printf("DCX    SP"); printf("\n"); break;
        case 0x3c: printf("INR    A"); printf("\n"); break;
        case 0x3d: printf("DRC    A"); printf("\n"); break;
        case 0x3e: printf("MVI    A,#$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0x3f: printf("CMC"); printf("\n"); break;
        case 0x40: printf("MOV    B,B"); printf("\n"); break;
        case 0x41: printf("MOV    B,C"); printf("\n"); break;
        case 0x42: printf("MOV    B,D"); printf("\n"); break;
        case 0x43: printf("MOV    B,E"); printf("\n"); break;
        case 0x44: printf("MOV    B,H"); printf("\n"); break;
        case 0x45: printf("MOV    B,L"); printf("\n"); break;
        case 0x46: printf("MOV    B,M"); printf("\n"); break;
        case 0x47: printf("MOV    B,A"); printf("\n"); break;
        case 0x48: printf("MOV    C,B"); printf("\n"); break;
        case 0x49: printf("MOV    C,C"); printf("\n"); break;
        case 0x4a: printf("MOV    C,D"); printf("\n"); break;
        case 0x4b: printf("MOV    C,E"); printf("\n"); break;
        case 0x4c: printf("MOV    C,H"); printf("\n"); break;
        case 0x4d: printf("MOV    C,L"); printf("\n"); break;
        case 0x4e: printf("MOV    C,M"); printf("\n"); break;
        case 0x4f: printf("MOV    C,A"); printf("\n"); break;
        case 0x50: printf("MOV    D,B"); printf("\n"); break;
        case 0x51: printf("MOV    D,C"); printf("\n"); break;
        case 0x52: printf("MOV    D,D"); printf("\n"); break;
        case 0x53: printf("MOV    D,E"); printf("\n"); break;
        case 0x54: printf("MOV    D,H"); printf("\n"); break;
        case 0x55: printf("MOV    D,L"); printf("\n"); break;
        case 0x56: printf("MOV    D,M"); printf("\n"); break;
        case 0x57: printf("MOV    D,A"); printf("\n"); break;
        case 0x58: printf("MOV    E,B"); printf("\n"); break;
        case 0x59: printf("MOV    E,C"); printf("\n"); break;
        case 0x5a: printf("MOV    E,D"); printf("\n"); break;
        case 0x5b: printf("MOV    E,E"); printf("\n"); break;
        case 0x5c: printf("MOV    E,H"); printf("\n"); break;
        case 0x5d: printf("MOV    E,L"); printf("\n"); break;
        case 0x5e: printf("MOV    E,M"); printf("\n"); break;
        case 0x5f: printf("MOV    E,A"); printf("\n"); break;
        case 0x60: printf("MOV    H,B"); printf("\n"); break;
        case 0x61: printf("MOV    H,C"); printf("\n"); break;
        case 0x62: printf("MOV    H,D"); printf("\n"); break;
        case 0x63: printf("MOV    H,E"); printf("\n"); break;
        case 0x64: printf("MOV    H,H"); printf("\n"); break;
        case 0x65: printf("MOV    H,L"); printf("\n"); break;
        case 0x66: printf("MOV    H,M"); printf("\n"); break;
        case 0x67: printf("MOV    H,A"); printf("\n"); break;
        case 0x68: printf("MOV    L,B"); printf("\n"); break;
        case 0x69: printf("MOV    L,C"); printf("\n"); break;
        case 0x6a: printf("MOV    L,D"); printf("\n"); break;
        case 0x6b: printf("MOV    L,E"); printf("\n"); break;
        case 0x6c: printf("MOV    L,H"); printf("\n"); break;
        case 0x6d: printf("MOV    L,L"); printf("\n"); break;
        case 0x6e: printf("MOV    L,M"); printf("\n"); break;
        case 0x6f: printf("MOV    L,A"); printf("\n"); break;
        case 0x70: printf("MOV    M,B"); printf("\n"); break;
        case 0x71: printf("MOV    M,C"); printf("\n"); break;
        case 0x72: printf("MOV    M,D"); printf("\n"); break;
        case 0x73: printf("MOV    M,E"); printf("\n"); break;
        case 0x74: printf("MOV    M,H"); printf("\n"); break;
        case 0x75: printf("MOV    M,L"); printf("\n"); break;
        case 0x76: printf("HLT"); printf("\n"); break;
        case 0x77: printf("MOV    M,A"); printf("\n"); break;
        case 0x78: printf("MOV    A,B"); printf("\n"); break;
        case 0x79: printf("MOV    A,C"); printf("\n"); break;
        case 0x7a: printf("MOV    A,D"); printf("\n"); break;
        case 0x7b: printf("MOV    A,E"); printf("\n"); break;
        case 0x7c: printf("MOV    A,H"); printf("\n"); break;
        case 0x7d: printf("MOV    A,L"); printf("\n"); break;
        case 0x7e: printf("MOV    A,M"); printf("\n"); break;
        case 0x7f: printf("MOV    A,A"); printf("\n"); break;
        case 0x80: printf("ADD    B"); printf("\n"); break;
        case 0x81: printf("ADD    C"); printf("\n"); break;
        case 0x82: printf("ADD    D"); printf("\n"); break;
        case 0x83: printf("ADD    E"); printf("\n"); break;
        case 0x84: printf("ADD    H"); printf("\n"); break;
        case 0x85: printf("ADD    L"); printf("\n"); break;
        case 0x86: printf("ADD    M"); printf("\n"); break;
        case 0x87: printf("ADD    A"); printf("\n"); break;
        case 0x88: printf("ADC    B"); printf("\n"); break;
        case 0x89: printf("ADC    C"); printf("\n"); break;
        case 0x8a: printf("ADC    D"); printf("\n"); break;
        case 0x8b: printf("ADC    E"); printf("\n"); break;
        case 0x8c: printf("ADC    H"); printf("\n"); break;
        case 0x8d: printf("ADC    L"); printf("\n"); break;
        case 0x8e: printf("ADC    M"); printf("\n"); break;
        case 0x8f: printf("ADC    A"); printf("\n"); break;
        case 0x90: printf("SUB    B"); printf("\n"); break;
        case 0x91: printf("SUB    C"); printf("\n"); break;
        case 0x92: printf("SUB    D"); printf("\n"); break;
        case 0x93: printf("SUB    E"); printf("\n"); break;
        case 0x94: printf("SUB    H"); printf("\n"); break;
        case 0x95: printf("SUB    L"); printf("\n"); break;
        case 0x96: printf("SUB    M"); printf("\n"); break;
        case 0x97: printf("SUB    A"); printf("\n"); break;
        case 0x98: printf("SBB    B"); printf("\n"); break;
        case 0x99: printf("SBB    C"); printf("\n"); break;
        case 0x9a: printf("SBB    D"); printf("\n"); break;
        case 0x9b: printf("SBB    E"); printf("\n"); break;
        case 0x9c: printf("SBB    H"); printf("\n"); break;
        case 0x9d: printf("SBB    L"); printf("\n"); break;
        case 0x9e: printf("SBB    M"); printf("\n"); break;
        case 0x9f: printf("SBB    A"); printf("\n"); break;
        case 0xa0: printf("ANA    B"); printf("\n"); break;
        case 0xa1: printf("ANA    C"); printf("\n"); break;
        case 0xa2: printf("ANA    D"); printf("\n"); break;
        case 0xa3: printf("ANA    E"); printf("\n"); break;
        case 0xa4: printf("ANA    H"); printf("\n"); break;
        case 0xa5: printf("ANA    L"); printf("\n"); break;
        case 0xa6: printf("ANA    M"); printf("\n"); break;
        case 0xa7: printf("ANA    A"); printf("\n"); break;
        case 0xa8: printf("XRA    B"); printf("\n"); break;
        case 0xa9: printf("XRA    C"); printf("\n"); break;
        case 0xaa: printf("XRA    D"); printf("\n"); break;
        case 0xab: printf("XRA    E"); printf("\n"); break;
        case 0xac: printf("XRA    H"); printf("\n"); break;
        case 0xad: printf("XRA    L"); printf("\n"); break;
        case 0xae: printf("XRA    M"); printf("\n"); break;
        case 0xaf: printf("XRA    A"); printf("\n"); break;
        case 0xb0: printf("ORA    B"); printf("\n"); break;
        case 0xb1: printf("ORA    C"); printf("\n"); break;
        case 0xb2: printf("ORA    D"); printf("\n"); break;
        case 0xb3: printf("ORA    E"); printf("\n"); break;
        case 0xb4: printf("ORA    H"); printf("\n"); break;
        case 0xb5: printf("ORA    L"); printf("\n"); break;
        case 0xb6: printf("ORA    M"); printf("\n"); break;
        case 0xb7: printf("ORA    A"); printf("\n"); break;
        case 0xb8: printf("CMP    B"); printf("\n"); break;
        case 0xb9: printf("CMP    C"); printf("\n"); break;
        case 0xba: printf("CMP    D"); printf("\n"); break;
        case 0xbb: printf("CMP    E"); printf("\n"); break;
        case 0xbc: printf("CMP    H"); printf("\n"); break;
        case 0xbd: printf("CMP    L"); printf("\n"); break;
        case 0xbe: printf("CMP    M"); printf("\n"); break;
        case 0xbf: printf("CMP    A"); printf("\n"); break;
        case 0xc0: printf("RNZ"); printf("\n"); break;
        case 0xc1: printf("POP    B"); printf("\n"); break;
        case 0xc2: printf("JNZ    $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xc3: printf("JMP    $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xc4: printf("CNZ    $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xc5: printf("PUSH   B"); printf("\n"); break;
        case 0xc6: printf("ADI    #$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0xc7: printf("RST    0"); printf("\n"); break;
        case 0xc8: printf("RZ"); printf("\n"); break;
        case 0xc9: printf("RET"); printf("\n"); break;
        case 0xca: printf("JZ     $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xcb: printf("NOP"); printf("\n"); break;
        case 0xcc: printf("CZ     $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xcd: printf("CALL   $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xce: printf("ACI    #$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0xcf: printf("RST    1"); printf("\n"); break;
        case 0xd0: printf("RNC"); printf("\n"); break;
        case 0xd1: printf("POP    D"); printf("\n"); break;
        case 0xd2: printf("JNC    $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xd3: printf("OUT    $%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0xd4: printf("CNC    $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xd5: printf("PUSH   D"); printf("\n"); break;
        case 0xd6: printf("SUI    #$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0xd7: printf("RST    2"); printf("\n"); break;
        case 0xd8: printf("RC"); printf("\n"); break;
        case 0xd9: printf("NOP"); printf("\n"); break;
        case 0xda: printf("JC     $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xdb: printf("IN     #$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0xdc: printf("CC     $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xdd: printf("NOP"); printf("\n"); break;
        case 0xde: printf("SBI    #$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0xdf: printf("RST    3"); printf("\n"); break;
        case 0xe0: printf("RPO"); printf("\n"); break;
        case 0xe1: printf("POP    H"); printf("\n"); break;
        case 0xe2: printf("JPO    $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xe3: printf("XTHL"); printf("\n"); break;
        case 0xe4: printf("CPO    $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xe5: printf("PUSH   H"); printf("\n"); break;
        case 0xe6: printf("ANI    #$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0xe7: printf("RST    4"); printf("\n"); break;
        case 0xe8: printf("RPE"); printf("\n"); break;
        case 0xe9: printf("PCHL"); printf("\n"); break;
        case 0xea: printf("JPE    $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xeb: printf("XCHG"); printf("\n"); break;
        case 0xec: printf("CPE    $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xed: printf("NOP"); printf("\n"); break;
        case 0xee: printf("XRI    #$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0xef: printf("RST    5"); printf("\n"); break;
        case 0xf0: printf("RP"); printf("\n"); break;
        case 0xf1: printf("POP    PSW"); printf("\n"); break;
        case 0xf2: printf("JP     $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xf3: printf("DI"); printf("\n"); break;
        case 0xf4: printf("CP     $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xf5: printf("PUSH   PSW"); printf("\n"); break;
        case 0xf6: printf("ORI    #$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0xf7: printf("RST    6"); printf("\n"); break;
        case 0xf8: printf("RM"); printf("\n"); break;
        case 0xf9: printf("SPHL"); printf("\n"); break;
        case 0xfa: printf("JM     $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xfb: printf("EI"); printf("\n"); break;
        case 0xfc: printf("CM     $%02x%02x", code[2], code[1]); opbytes = 3; printf("\n"); break;
        case 0xfd: printf("NOP"); printf("\n"); break;
        case 0xfe: printf("CPI    #$%02x", code[1]); opbytes = 2; printf("\n"); break;
        case 0xff: printf("RST    7"); printf("\n"); break;
    }
    return opbytes;
}
